openapi: 3.0.3
info:
  title: Marketplace Ads API
  version: 1.1.0
  description: API-спецификация для сервиса управления объявлениями в приложении маркетплейса.

servers:
  - url: https://marketplace.swagger.io/api/ads
tags:
  - name: Работа с объявлениями
    description: Список эндпоинтов, позволяющих работать с объявлениями
paths:

  /ads:
    post:
      tags:
        - Работа с объявлениями
      security:
      - BearerAuth: [] 
      summary: Создать объявление
      description: Создает объявление, присваивая ему статус "Prototype"
      parameters:
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            type: string
            format: uuid
            example: 8e03978e-40d5-43e8-bc93-6894a57f9324
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdCreate'
      responses:
        '202':
          description: Объявление принято в обработку
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        

    get:
      tags:
        - Работа с объявлениями
      security:
      - BearerAuth: [] 
      summary: Получить список объявлений
      description: Возвращает список объявлений пользователя
      parameters:
        - name: category
          in: query
          description: Фильтр по категории объявления
          schema:
            type: string
            example: Иностранные языки

        - name: minPrice
          in: query
          description: Минимальная цена
          schema:
            type: number
            example: 1000

        - name: maxPrice
          in: query
          description: Максимальная цена
          schema:
            type: number
            example: 3000

        - name: search
          in: query
          description: Поиск по названию и описанию объявления
          schema:
            type: string
            example: английский

        - name: sort
          in: query
          description: Поле сортировки
          schema:
            type: string
            enum: [price, createdAt]
            example: price

        - name: order
          in: query
          description: Направление сортировки
          schema:
            type: string
            enum: [asc, desc]
            example: asc

        - name: limit
          in: query
          description: Количество элементов на странице
          schema:
            type: number
            example: 10

        - name: offset
          in: query
          description: Смещение для пагинации
          schema:
            type: integer
            example: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdTakeAll'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /ads/{idAd}:
    get:
      tags:
        - Работа с объявлениями
      security:
      - BearerAuth: [] 
      summary: Получить объявление по id
      description: Возвращает выбраное по id обьявление
      parameters:
        - name: idAd
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: Версия ресурса
              schema:
                type: string
                example: "\"v1.675afc\""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdTake'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

    patch:
      tags:
        - Работа с объявлениями
      security:
      - BearerAuth: [] 
      summary: Изменить объявление
      description: Позволяет изменить объявление (Название, категорию,  описание, цена)
      parameters:
        - name: idAd
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: If-Match
          in: header
          required: true
          description: ETag 
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdUpdate'
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: Новая версия ресурса после изменения
              schema:
                type: string
                example: "\"v2.89ab12\""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdTake'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - Работа с объявлениями
      security:
      - BearerAuth: [] 
      summary: Удалить объявление
      parameters:
        - name: idAd
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Удалено
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  

  /moderation/ads/{idAd}/decision:
    post:
      tags:
        - Работа с объявлениями
      security:
      - BearerAuth: [] 
      summary: Решение модератора
      description: Модератор принимает решение об подтверждении или отклонении обьявления пользователя
      parameters:
        - name: idAd
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            type: string
            format: uuid
            example: 8e03978e-40d5-43e8-bc93-6894a57f9324
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModerationDecision'
      responses:
        '200':
          description: Выполнено
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AdCreate:
      type: object
      description: Данные для создания нового объявления.
      required: [userId, adCategory, adDescription, adName, adPrice]
      properties:
        userId:
          type: string
          description: Уникальный идентификатор пользователя
          format: uuid
          example: "ce7f56fa-19d2-4432-a1f7-9ac8453fcd3b"
        adName:
          type: string
          description: Заголовок объявления
          minLength: 3
          maxLength: 100
          example: "Анлийский язык"
        adPrice:
          type: number
          description: Цена услуги
          minimum: 0
          example: 1500
        adCategory:
          type: string
          description: Категория услуги
          minLength: 3
          maxLength: 100
          example: Иностраные языки
        adDescription:
          type: string
          description: Описание условий и характеристик объявления
          minLength: 3
          maxLength: 500
          example: Курсы английского языка, начиная с уровня А1 и до уровня С2.

    AdInfo:
      type: object
      description: Полная информация об объявлении
      required: [idAd, userId, adCategory, adDescription, adName, adPrice, AdStatus, _links]
      properties:
        idAd:
          type: string
          description: Уникальный идентификатор объявления
          format: uuid
          example: "dhe64ks0-3t6s-5620-s6rn-23djr6y85wnf"
        userId:
          type: string
          description: Уникальный идентификатор пользователя
          format: uuid
          example: "ce7f56fa-19d2-4432-a1f7-9ac8453fcd3b"
        userName:
          type: string
          description: ФИО пользователя
          minLength: 3
          maxLength: 100
          example: "Бобров Сергей Викторович"
        userDescription:
          type: string
          description: Биография пользователя
          minLength: 3
          maxLength: 500
          example: "Преподаю английский язык для школьников и студентов."
        userRating:
          type: number
          description: Рейтинг пользователя
          minimum: 0.1
          maximum: 5
          example: 4.4
        userPFP:
          type: string
          description: Аватар пользователя
          format: uri
          example: https://cdn.example.com/users/ce7f56fa/avatar.jpg
        adName:
          type: string
          description: Заголовок объявления
          minLength: 3
          maxLength: 100
          example: "Анлийский язык"
        adPrice:
          type: number
          description: Цена услуги
          minimum: 0
          example: 1500
        adCategory:
          type: string
          description: Категория услуги
          minLength: 3
          maxLength: 100
          example: Иностраные языки
        adDescription:
          type: string
          description: Описание объявления
          minLength: 3
          maxLength: 500
          example: Курсы английского языка, начиная с уровня А1 и до уровня С2.
        status:
          type: string
          description: Статус объявления
          enum: [Prototype, Moderation, Publish, Cancel]
        _links:
          type: array
          description: HATEOAS-ссылки
          minItems: 1
          items:
            $ref: '#/components/schemas/HateoasLink'
          example: 
            - rel: self
              method: GET
              href: /api/v1/ads/dhe64ks0-3t6s-5620-s6rn-23djr6y85wnf
              description: Получить объявление
            - rel: update
              method: PATCH
              href: /api/v1/ads/dhe64ks0-3t6s-5620-s6rn-23djr6y85wnf
              description: Изменить объявление
            - rel: delete
              method: DELETE
              href: /api/v1/ads/dhe64ks0-3t6s-5620-s6rn-23djr6y85wnf
              description: Удалить объявление
    
    AdUpdate:
      type: object
      description: Данные для обновления объявления
      required: [adName, adPrice, adCategory, adDescription]
      properties:
        adName:
          type: string
          description: Заголовок объявления
          minLength: 3
          maxLength: 100
          example: "Анлийский язык"
        adPrice:
          type: number
          description: Цена услуги
          minimum: 0
          example: 1500
        adCategory:
          type: string
          description: Категория услуги
          minLength: 3
          maxLength: 100
          example: Иностраные языки
        adDescription:
          type: string
          description: Описание объявления
          minLength: 3
          maxLength: 500
          example: Курсы английского языка, начиная с уровня А1 и до уровня С2.

    AdTake:
      type: object
      description: Ответ с полученным объявлением и метаданными ресурса
      required: [items, countOfReplys, maximumOfReplys, startFrom]
      properties:
        items:
          type: array
          description: Массив с перечнем данных о полученном объявлении
          minItems: 1
          items:
            $ref: '#/components/schemas/AdInfo'
        createdAt:
          type: string
          description: Дата и время создания записи
          format: date-time
          example: 2023-10-27 15:30:00
        updatedAt:
          type: string
          description: Дата и время последнего изменения записи
          format: date-time
          example: 2023-10-27 15:40:00
        _etag:
          type: string
          description: Уникальный идентификатор версии ресурса
          example: "\"v1.675afc\""
        _version:
          type: string
          description: Версия ресурса
          example: v1  

    AdTakeAll:
      type: object
      description: Ответ со списком объявлений
      required: [items, countOfReplys, maximumOfReplys, startFrom]
      properties:
        items:
          type: array
          description: 
          minItems: 1
          items:
            $ref: '#/components/schemas/AdInfo'
        countOfReplys:
          type: number
          description: Количество полученных записей
          example: 7
        maximumOfReplys:
          type: number
          description: Максимальное допустопие количество  записей для получения
          maximum: 15
          example: 15
        startFrom:
          type: number
          description: Позиция получения записей
          example: 2
        _links:
          type: object
          description: Навигационные ссылки для постраничного просмотра
          properties:
            curr:
              type: string
              format: uri
              description: Текущая страница
            next:
              type: string
              format: uri
              description: Следующая страница
            prev:
              type: string
              format: uri
              description: Предыдущая страница
          example:
            curr: https://page.com/
            next: https://page.com/?page=2
            prev: https://page.com/?page=0
        
    HateoasLink:
      type: object
      description: Описание гиперссылки действия
      required: [rel, method, href]
      properties:
        rel:
          type: string
          description: Тип связи
          example: self
        method:
          type: string
          enum: [GET, POST, PATCH, DELETE]
          example: GET
        href:
          type: string
          example: /api/v1/ads/dhe64ks0-3t6s-5620-s6rn-23djr6y85wnf
        description:
          type: string
          maxLength: 200
          example: Получить объявление

    AsyncOperationResponse:
      type: object
      description: Ответ для асинхронных операций
      properties:
        operationId:
          type: string
          description: Уникальный идентификатор асинхронной операции
          format: uuid
          example: "ce7f56fa-19d2-4432-a1f7-9ac8453fcd3b"
        statusAdLink:
          description: Ссылка на статус асинхронной операции
          example: "/ads/operations/ce7f56fa-19d2-4432-a1f7-9ac8453fcd3b"

    ModerationDecision:
      type: object
      description: Решение модератора по объявлению
      required: [decision, reason]
      properties:
        decision:
          type: string
          enum:
            - APPROVE
            - REJECT
          description: Решение модератора
        reason:
          type: string
          minLength: 5
          maxLength: 500
          description: Причина отказа (обязательно при REJECT)


  responses:
    BadRequest:
      description: Ошибка валидации
    NotFound:
      description: Ресурс не найден
    PreconditionFailed:
      description: Ресурс заблокирован
    Timeout:
      description: Таймаут
    TooManyRequests:
      description: Превышен лимит запросов
    Conflict:
      description: Конфликт состсояний ресурса
    InternalServerError:
      description: Внутрення ошибка сервера
